In [22]:
import cv2
import mediapipe as mp

# Initialize MediaPipe hands and drawing utilities
mp_hands = mp.solutions.hands
mp_drawing = mp.solutions.drawing_utils
mp_drawing_styles = mp.solutions.drawing_styles

# Load an image with a hand
image_path = r'C:\Users\Admin\Desktop\DAP391m\sign language\sign-language-detector-python\data_test\0\hand1_n_dif_seg_5_cropped.jpeg'  # Replace with your image path
img = cv2.imread(image_path)
print(img)
# Convert the image to RGB (MediaPipe requires RGB input)
img_rgb = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)

# Initialize the MediaPipe Hands model
hands = mp_hands.Hands(static_image_mode=True, min_detection_confidence=0.3)

# Process the image to detect hand landmarks
results = hands.process(img_rgb)
# Check if hand landmarks are detected
if results.multi_hand_landmarks:
    for hand_landmarks in results.multi_hand_landmarks:
        # Draw hand landmarks on the original image
        mp_drawing.draw_landmarks(
            img,  # Image to draw on
            hand_landmarks,  # Hand landmarks detected
            mp_hands.HAND_CONNECTIONS,  # Draw the connections between landmarks
            mp_drawing_styles.get_default_hand_landmarks_style(),  # Style for landmarks
            mp_drawing_styles.get_default_hand_connections_style()  # Style for connections
        )

# Display the image with landmarks drawn
cv2.imshow('Hand Landmarks', img)

# Wait for a key press to close the window
cv2.waitKey(0)
cv2.destroyAllWindows()


[[[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 ...

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]]


In [25]:
import cv2
import numpy as np

# Load the hand image (your original image)
image_path = r'C:\Users\Admin\Desktop\DAP391m\sign language\sign-language-detector-python\data_test\0\hand1_n_dif_seg_5_cropped.jpeg' 
img = cv2.imread(image_path, cv2.IMREAD_UNCHANGED)

# Create a black background of size 800x600
background_height = 600
background_width = 800
black_background = np.zeros((background_height, background_width, 3), dtype=np.uint8)

# Handle transparency if the image has an alpha channel
if img.shape[2] == 4:  # Image has an alpha channel
    # Split the image into BGR and Alpha channel
    bgr, alpha = img[:, :, :3], img[:, :, 3]

    # Create a blank black background for the hand image
    hand_img_black_bg = np.zeros_like(bgr)

    # Apply the alpha mask to combine the hand with the black background
    hand_on_black = cv2.bitwise_or(hand_img_black_bg, bgr, mask=alpha)
else:
    # If no alpha channel, just use the BGR image directly
    hand_on_black = img

# Get the size of the hand image
hand_height, hand_width = hand_on_black.shape[:2]

# Calculate the position to center the hand image within the 800x600 background
y_offset = (background_height - hand_height) // 2
x_offset = (background_width - hand_width) // 2

# Insert the hand image into the center of the black background
black_background[y_offset:y_offset + hand_height, x_offset:x_offset + hand_width] = hand_on_black

# Save the resulting image
output_path = 'hand_on_800x600_black_background.png'  # Output path
# cv2.imwrite(output_path, black_background)

# Display the result (optional)
cv2.imshow('Hand on Black Background', black_background)
cv2.waitKey(0)
cv2.destroyAllWindows()


In [26]:
import cv2
import mediapipe as mp

# Initialize MediaPipe hands and drawing utilities
mp_hands = mp.solutions.hands
mp_drawing = mp.solutions.drawing_utils
mp_drawing_styles = mp.solutions.drawing_styles

# Load an image with a hand
image_path = r'C:\Users\Admin\Desktop\DAP391m\sign language\sign-language-detector-python\data_test\0\hand1_n_dif_seg_5_cropped.jpeg'  # Replace with your image path
img = black_background

# Convert the image to RGB (MediaPipe requires RGB input)
img_rgb = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)

# Initialize the MediaPipe Hands model
hands = mp_hands.Hands(static_image_mode=True, min_detection_confidence=0.3)

# Process the image to detect hand landmarks
results = hands.process(img_rgb)
print(len(results.multi_hand_landmarks))
# Check if hand landmarks are detected
if results.multi_hand_landmarks:
    for hand_landmarks in results.multi_hand_landmarks:
        # Draw hand landmarks on the original image
        mp_drawing.draw_landmarks(
            img,  # Image to draw on
            hand_landmarks,  # Hand landmarks detected
            mp_hands.HAND_CONNECTIONS,  # Draw the connections between landmarks
            mp_drawing_styles.get_default_hand_landmarks_style(),  # Style for landmarks
            mp_drawing_styles.get_default_hand_connections_style()  # Style for connections
        )

# Display the image with landmarks drawn
cv2.imshow('Hand Landmarks', img)

# Wait for a key press to close the window
cv2.waitKey(0)
cv2.destroyAllWindows()


1
